name: new_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/less.svg
    - assets/icons/two-dots.svg
    - assets/icons/search.svg
    - assets/icons/filter.svg
    - assets/icons/ice-cream.svg
    - assets/icons/pancake.svg
    - assets/icons/pie.svg
    - assets/icons/salad.svg
    - assets/icons/action.svg
    - assets/icons/user-1.svg
    - assets/images/heroBG.jpg
    - assets/icons/pd.svg
    - assets/icons/G.svg
    - assets/icons/G-1.svg
    - assets/icons/G-2.svg
    - assets/images/house1.jpg
    - assets/images/kitchen.jpg
    - assets/images/house2.jpg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
